### PR TITLE
Add rook analyze injector

### PR DESCRIPTION
**Pull request by moonlight16**

### CODE REVIEW

**Comment by marccampbell** [comment]
@moonlight16 let's move these into a `rook` collector instead of a collection of ad-hoc execs and runs.

**Comment by moonlight16** [comment]
@marccampbell yes, this PR was opened prior to our discussion today.  I will be reworking the rook collector and analyzer into the troubleshoot repo.

**Comment by moonlight16** [comment]
FWIW, here's the PR for the supporting code over in the troubleshoot repo:
https://github.com/replicatedhq/troubleshoot/pull/150

**Comment by marccampbell** [comment]
This was ported over to a Go implementation and no longer relevant

**Pull request closed without merging**
